### ISSUE TITLE
Can't install package on python 3.12

### ISSUE THREAD

**Issue by dule91sd** [JohannesBuchner/imagehash#196]
When I want to install package on python 3.12 i got an error:
```
Defaulting to user installation because normal site-packages is not writeable
Collecting imagehash
  Using cached ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
Collecting PyWavelets (from imagehash)
  Using cached PyWavelets-1.4.1.tar.gz (4.6 MB)
  Installing build dependencies ... done  
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

But it's works on 3.11.
What can be a problem?

**Comment by JohannesBuchner** [comment]
duplicate of #194
